---
- name: Run Jinja2 Template to Generate Cisco Commands
  hosts: "{{ variable_host }}"
  gather_facts: no

  vars_prompt:
    - name: "variable_host"
      prompt: "Host or Host Group"
      private: no

    - name: "ansible_user"
      prompt: "Username"
      private: no

    - name: "ansible_ssh_pass"
      prompt: "Password"
      private: yes

  tasks:
    - name: Render Jinja2 template for commands
      template:
        src: match_commands.j2
        dest: /tmp/match_commands.txt

    - name: Read commands from the rendered template
      slurp:
        src: /tmp/match_commands.txt
      register: command_file

    - name: Decode commands from base64
      set_fact:
        command_list: "{{ command_file.content | b64decode | split('\n') }}"

    - name: Send commands with timeout
      cli_command:
        command: "{{ item }}"
      loop: "{{ command_list }}"
      register: result_iosxr
      vars:
        ansible_command_timeout: 60  # Set command timeout to 60 seconds

    - name: Overwrite firstrun file with new results
      copy:
        content: "{{ result_iosxr.results | map(attribute='stdout') | join('\n') }}"
        dest: "~/Ansible/MISC/results.go"
        mode: '0644'
        force: yes  # Ensures the file is overwritten

    - name: Print IOS XR debug info
      debug:
        var: result_iosxr.stdout_lines
